# numpy基础

In [31]:
import numpy as np

array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]],dtype = np.int64)#位数越小，占用空间越小，但不精确

print(array)

(array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]),)


In [12]:
print('number of dim:', array.ndim)#输出纬度

number of dim: 2


In [13]:
print('sgape:', array.shape)#行数

sgape: (3, 3)


In [10]:
print('size:', array.size)#元素个数

size: 6


In [24]:
print(array.dtype)

int64


In [26]:
a = np.zeros((3,4))

In [27]:
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [28]:
b = np.ones((3,4))
print(b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [33]:
c = np.empty((3,4))
print(c)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [34]:
d = np.arange(10,20,2)
print(d)

[10 12 14 16 18]


In [35]:
e = np.arange(12).reshape((3,4))
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
f = np.linspace(1,10,20).reshape((5,4))
print(f)

[[  1.           1.47368421   1.94736842   2.42105263]
 [  2.89473684   3.36842105   3.84210526   4.31578947]
 [  4.78947368   5.26315789   5.73684211   6.21052632]
 [  6.68421053   7.15789474   7.63157895   8.10526316]
 [  8.57894737   9.05263158   9.52631579  10.        ]]


In [54]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
c = a-b
print(c)
d = b**2  #几次方使用双星号
print(d)
e = 10*np.sin(a)
print(e)
print(a<15)
print(b==3)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True False False False]
[False False False  True]


In [69]:
a = np.array([[1,1],
            [0,1]],)
b = np.arange(4).reshape(2,2)
print(a)
print(b)

c = a*b  #逐个相乘
d = np.dot(a,b)#矩阵乘法
e = a.dot(b)

print(c)
print(d)

if d.all() == e.all():
    print("true")
else:
    print("false")

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
true


In [146]:
a = np.random.random((2,4))
print(a)
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print("行求和:",np.sum(a, axis=1))
print("列求和:",np.sum(a, axis=0))
print("每一行重的最大值：",np.max(a, axis=1))
print("每一列中的最小值：",np.min(a, axis=0))

[[ 0.44887332  0.29351536  0.4955915   0.31650077]
 [ 0.17605892  0.19689103  0.26861157  0.34020782]]
2.53625027806
0.495591499407
0.176058919993
行求和: [ 1.55448095  0.98176933]
列求和: [ 0.62493224  0.49040638  0.76420307  0.65670859]
每一行重的最大值： [ 0.4955915   0.34020782]
每一列中的最小值： [ 0.17605892  0.19689103  0.26861157  0.31650077]


In [147]:
A = np.arange(14,2,-1).reshape((3,4))
print(A)
print('-------------')
print('最小值索引:',np.argmin(A))
print('最大值索引:',np.argmax(A))
print('-------------')
print('平均值:', np.mean(A))
print('平均值:', A.mean())
print('平均值:',np.average(A))
print('-------------')
print('中位数:',np.median(A))
print('-------------')
print('累加:',np.cumsum(A))
print('-------------')
print('累差:',np.diff(A))
print('-------------')
print('对应位置:',np.nonzero(A))
print('-------------')
print('逐行排序:',np.sort(A))
print('-------------')
print('矩阵反向:',np.transpose(A))
print('矩阵反向:',A.T)
print('-------------')
print('矩阵乘法:',(A.T).dot(A))
print('-------------')
print('变换:',np.clip(A,5,9))#所有小于5的数都等于5，所有大于9的数都等于9,中间的数保持不变
print('-------------')
print(':',np.mean(A,axis=0))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
-------------
最小值索引: 11
最大值索引: 0
-------------
平均值: 8.5
平均值: 8.5
平均值: 8.5
-------------
中位数: 8.5
-------------
累加: [ 14  27  39  50  60  69  77  84  90  95  99 102]
-------------
累差: [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
-------------
对应位置: (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
-------------
逐行排序: [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
-------------
矩阵反向: [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
矩阵反向: [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
-------------
矩阵乘法: [[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
-------------
变换: [[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
-------------
: [ 10.   9.   8.   7.]


In [148]:
A = np.arange(3,15).reshape((3,4))
count = 0
print(A)
print('-------------------------')
print(A[2][3])
print('-------------------------')
print(A[2, 3])
print('-------------------------')
print('第3行：',A[2, :])
print('-------------------------')
print('第2列：',A[:, 1])
print('-------------------------')
for row in A:
    count += 1
    print('打印',count,'行:',row)
print('-------------------------')
count = 0
for column in A.T:
    count += 1
    print('打印',count,'列:',column)
print('-------------------------')
print(A.flatten())#迭代器
print('输出每一项:')
for item in A.flat:
    print(item)
print('-------------------------')

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
-------------------------
14
-------------------------
14
-------------------------
第3行： [11 12 13 14]
-------------------------
第2列： [ 4  8 12]
-------------------------
打印 1 行: [3 4 5 6]
打印 2 行: [ 7  8  9 10]
打印 3 行: [11 12 13 14]
-------------------------
打印 1 列: [ 3  7 11]
打印 2 列: [ 4  8 12]
打印 3 列: [ 5  9 13]
打印 4 列: [ 6 10 14]
-------------------------
[ 3  4  5  6  7  8  9 10 11 12 13 14]
输出每一项:
3
4
5
6
7
8
9
10
11
12
13
14
-------------------------


# numpy array合并

In [153]:
A = np.array([1,1,1])
B = np.array([2,2,2])
print('-------------------------')
print(np.vstack((A, B)))     #AB上下合并
print('-------------------------')
C = np.vstack((A, B))
print(A.shape, C.shape)
print('-------------------------')
print(np.hstack((A, B)))     #AB左右合并
D = np.hstack((A, B))
print(A.shape, D.shape)
print('-------------------------')
print(A[np.newaxis,:])  #将A从序列转为矩阵,在横向加一个纬度
print(A[np.newaxis,:].shape)
print(A[:,np.newaxis])  #将A从序列转为矩阵,在纵向加一个纬度
print('-------------------------')
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(np.vstack((A, B)))
print(np.hstack((A, B)))
print('-------------------------')
C = np.concatenate((A,B,A,B))
print(C)
print('-------------------------')
D = np.concatenate((A,B,A,B),axis = 1)#axis=0是上下合并，=1是左右合并
print(D)
print('-------------------------')
print('-------------------------')
print('-------------------------')

-------------------------
[[1 1 1]
 [2 2 2]]
-------------------------
(3,) (2, 3)
-------------------------
[1 1 1 2 2 2]
(3,) (6,)
-------------------------
[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
-------------------------
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
-------------------------
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]
-------------------------
[[1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]]
-------------------------
-------------------------
-------------------------


# numpy array分割

In [155]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
